import os
import json
import re
import numpy as np
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse, JSONResponse
from pydantic import BaseModel
from sentence_transformers import SentenceTransformer
from groq import Groq

from dotenv import load_dotenv

load_dotenv()

# Initialize FastAPI App
app = FastAPI(
    title="Local Services AI Engine",
    description="Matching Engine & AI Support Assistant microservice",
    version="1.0.0"
)

# CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# 1. Initialize SentenceTransformers Embeddings Model
print("Loading embedding model...")
embedder = SentenceTransformer('all-MiniLM-L6-v2')

# 2. Initialize Groq LLM Client
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
groq_client = Groq(api_key=GROQ_API_KEY) if GROQ_API_KEY else None
GROQ_MODEL = "deepseek-r1-distill-llama-70b"

# Pre-defined Service Categories (10 items)
CATEGORIES = [
    {
        "id": "cat_01",
        "name": "AC Repair & Installation",
        "desc": "Air conditioner repair, gas refilling, split AC indoor unit leak, compressor check, master servicing, split AC installation."
    },
    {
        "id": "cat_02",
        "name": "Plumbing & Leak Fix",
        "desc": "Pipe leaks, tap repairs, sink drain unblocking, bathroom fitting, water tank cleaning, burst pipes, water line repairs."
    },
    {
        "id": "cat_03",
        "name": "Electrical Work",
        "desc": "Short circuits, wiring, switchboard installation, light fixture fitting, circuit breaker replacement, UPS wiring."
    },
    {
        "id": "cat_04",
        "name": "Appliance Repair",
        "desc": "Washing machine repair, refrigerator cooling issues, microwave oven repair, water dispenser fix, deep freezer repair."
    },
    {
        "id": "cat_05",
        "name": "Home Cleaning",
        "desc": "Deep home cleaning, sofa & carpet shampooing, post-renovation cleanup, kitchen deep clean, window washing."
    },
    {
        "id": "cat_06",
        "name": "Carpentry & Furniture",
        "desc": "Door lock repair, custom furniture assembly, cabinet repair, wooden table polish, hinge fix."
    },
    {
        "id": "cat_07",
        "name": "Painting & Waterproofing",
        "desc": "Interior wall painting, exterior wall painting, roof seepage waterproofing, wall moisture repair, stencil paint."
    },
    {
        "id": "cat_08",
        "name": "Pest Control",
        "desc": "Termite treatment, cockroach spray, bed bug eradication, rodent control, mosquito fumigation."
    },
    {
        "id": "cat_09",
        "name": "CCTV & Security Systems",
        "desc": "CCTV camera installation, DVR setup, security sensor wiring, smart lock installation, intercom repair."
    },
    {
        "id": "cat_10",
        "name": "Solar Panel Servicing",
        "desc": "Solar panel cleaning, inverter troubleshooting, solar wiring inspection, battery system maintenance."
    }
]

from faq_data import FAQ_DOC

print("Pre-computing category embeddings...")
for cat in CATEGORIES:
    cat["embedding"] = embedder.encode(cat["name"] + ": " + cat["desc"])

print("Pre-computing FAQ embeddings...")
faq_embeddings = [{"text": faq, "vector": embedder.encode(faq)} for faq in FAQ_DOC]
print("AI Engine ready.")

def cosine_sim(v1, v2):
    return float(np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2)))

def clean_response(text: str) -> str:
    """
    Robustly strip any internal <think> reasoning tags generated by LLM,
    including unclosed <think>... blocks if response was cut off by token limit.
    """
    if not text:
        return ""
    cleaned = re.sub(r'(?i)<think>.*?</think>', '', text, flags=re.DOTALL)
    cleaned = re.sub(r'(?i)<think>.*$', '', cleaned, flags=re.DOTALL)
    return cleaned.strip()

def call_groq(prompt, max_tokens=1024, json_mode=False, system_prompt=None):
    """Helper to call Groq LLM with higher max_tokens & robust reasoning cleanup."""
    if not groq_client:
        return None
    try:
        sys_msg = system_prompt or "You are a customer support AI assistant. Respond directly to the user in 1-3 sentences. NEVER output <think> tags, thinking traces, or reasoning steps."
        kwargs = {
            "model": GROQ_MODEL,
            "messages": [
                {"role": "system", "content": sys_msg},
                {"role": "user", "content": prompt}
            ],
            "max_tokens": max_tokens,
            "temperature": 0.2 if json_mode else 0.5,
        }
        if json_mode:
            kwargs["response_format"] = {"type": "json_object"}
        response = groq_client.chat.completions.create(**kwargs)
        raw = response.choices[0].message.content or ""
        return clean_response(raw)
    except Exception as e:
        if json_mode:
            try:
                kwargs_no_fmt = {
                    "model": GROQ_MODEL,
                    "messages": [
                        {"role": "system", "content": (system_prompt or "") + " Return ONLY a valid raw JSON object. No extra text or markdown."},
                        {"role": "user", "content": prompt}
                    ],
                    "max_tokens": max_tokens,
                    "temperature": 0.2,
                }
                response = groq_client.chat.completions.create(**kwargs_no_fmt)
                raw = response.choices[0].message.content or ""
                cleaned = clean_response(raw)
                match = re.search(r'\{.*\}', cleaned, re.DOTALL)
                return match.group(0) if match else cleaned
            except Exception as e2:
                print(f"Groq fallback retry error: {e2}")
                return None
        print(f"Groq API error: {e}")
        return None

# HTML Frontend
try:
    with open("index.html", "r", encoding="utf-8") as f:
        HTML_CONTENT = f.read()
except Exception:
    HTML_CONTENT = "<h1>AI Services Operational</h1>"

@app.get("/", response_class=HTMLResponse)
def get_dashboard():
    return HTML_CONTENT

# 1. Matching Engine Endpoint
class MatchRequest(BaseModel):
    customer_request: str

@app.post("/ai/match")
def match_category(req: MatchRequest):
    user_text = req.customer_request.strip()

    # --- Strategy A: High-Precision Groq LLM Intent Classification ---
    categories_prompt_list = "\n".join([f"- {cat['id']}: {cat['name']} ({cat['desc']})" for cat in CATEGORIES])
    llm_prompt = f"""Classify this customer service request into exactly ONE of the 10 available service categories:

Customer Request: "{user_text}"

Available Categories:
{categories_prompt_list}

Rules:
1. Pay attention to the core appliance/equipment context (e.g. split AC indoor unit leaking water is an AC Repair issue, not general plumbing).
2. Return ONLY valid JSON with no extra text or thinking tags:
{{
    "matched_category_id": "cat_01",
    "matched_category_name": "AC Repair & Installation",
    "confidence_score": 0.95
}}
"""

    llm_result = call_groq(
        prompt=llm_prompt,
        max_tokens=250,
        json_mode=True,
        system_prompt="You are a strict text classification system for local service requests. Return ONLY valid JSON."
    )

    if llm_result:
        try:
            data = json.loads(llm_result)
            cat_id = data.get("matched_category_id")
            confidence = float(data.get("confidence_score", 0.90))

            matching_cat = next((c for c in CATEGORIES if c["id"] == cat_id), None)
            if matching_cat:
                return {
                    "status": "success",
                    "matched_category_id": matching_cat["id"],
                    "matched_category_name": matching_cat["name"],
                    "confidence_score": confidence
                }
        except Exception as e:
            print(f"LLM match JSON parse error: {e}")

    # --- Strategy B: Fallback to Enriched Sentence Transformers Embeddings ---
    user_vec = embedder.encode(user_text)
    best, score = max(
        ((cat, cosine_sim(user_vec, cat["embedding"])) for cat in CATEGORIES),
        key=lambda x: x[1]
    )
    if score >= 0.35:
        return {
            "status": "success",
            "matched_category_id": best["id"],
            "matched_category_name": best["name"],
            "confidence_score": score
        }
    return {
        "status": "fallback",
        "matched_category_id": "manual",
        "message": "Confidence too low. Manual selection required.",
        "confidence_score": score
    }

# 2. Bio Generator (Groq LLM)
class BioRequest(BaseModel):
    provider_name: str
    skills: list[str]
    years_experience: int
    tone: str

@app.post("/ai/generate-bio")
def generate_bio(req: BioRequest):
    skills_str = ", ".join(req.skills)
    prompt = f"""Write a 2-paragraph professional biography for a local service provider.
Name: {req.provider_name}
Skills: {skills_str}
Experience: {req.years_experience} years
Tone: {req.tone}
Rules: Return ONLY the biography text. No markdown. Sound human and trustworthy."""

    result = call_groq(prompt, max_tokens=400)
    if result:
        return {"status": "success", "bio": result}
    return {
        "status": "success",
        "bio": f"{req.provider_name} is a highly dedicated professional with {req.years_experience} years of experience specializing in {skills_str}. Known for exceptional quality, punctuality, and customer satisfaction."
    }

# 3. Support Chatbot (Groq LLM + FAQ RAG)
class ChatRequest(BaseModel):
    user_message: str

def format_faq_answer(text: str) -> str:
    """Strip leading FAQ topic prefixes (e.g. 'How to Cancel: ...') so answer is direct."""
    if not text:
        return ""
    if ":" in text:
        parts = text.split(":", 1)
        if len(parts[1].strip()) > 10:
            return parts[1].strip()
    return text.strip()

@app.post("/ai/chat")
def support_chat(req: ChatRequest):
    query = req.user_message.strip()
    query_vec = embedder.encode(query)

    # RAG: Retrieve top 2 FAQ context
    faq_scores = [(item["text"], cosine_sim(query_vec, item["vector"])) for item in faq_embeddings]
    faq_scores.sort(key=lambda x: x[1], reverse=True)
    top_context = "\n".join([item[0] for item in faq_scores[:2]])

    prompt = f"""FAQ Context:
{top_context}

User Question: "{query}"

Answer the user's question clearly, warmly, and helpfully in 1 to 3 sentences based on the context above. NEVER output <think> tags or reasoning steps."""

    reply = call_groq(
        prompt=prompt,
        max_tokens=300,
        system_prompt="You are a friendly customer support AI assistant for Local Services Marketplace. Answer concisely in 1-3 sentences. NEVER output <think> tags."
    )
    if not reply:
        best_match_text, best_score = faq_scores[0]
        if best_score >= 0.20:
            reply = format_faq_answer(best_match_text)
        else:
            reply = "I'm here to assist with any questions about bookings, cancellations, payments, or provider registration! Feel free to ask anytime."
    else:
        reply = format_faq_answer(reply)

    return {
        "status": "success",
        "reply": reply,
        "response": reply
    }
